modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
issueTrackerURL="https://github.com/eerussianguy/Combat-Music/issues"
[[mods]] #mandatory
modId="combat_music" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Combat Music" #mandatory
displayURL="https://github.com/eerussianguy/Combat-Music"
logoFile="examplemod.png" #optional
#credits="Thanks to..." #optional
authors="EERussianguy" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Mod that causes music cues during combat.

Leave issues on the github please.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.combat_music]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.combat_music]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
